"""Canonical sparse model representation."""

from qqa.model.ir import (
    AllDifferentFactor,
    AssignmentFactor,
    BlackBoxFactor,
    CardinalityFactor,
    ClauseFactor,
    ConstraintIR,
    HigherOrderFactor,
    LinearFactor,
    ModelIR,
    ModelMetadata,
    ObjectiveIR,
    ObjectiveSense,
    PairwisePottsFactor,
    QuadraticEdgeFactor,
    TableFactor,
    TransformationRecord,
    VariableBlock,
    VariableDomain,
)
from qqa.model.native import (
    CumulativeResourceFactor,
    FlowConservationFactor,
    IndicatorFactor,
    LogicalFactor,
    MatchingFactor,
    NoOverlapFactor,
    PiecewiseLinearFactor,
    PrecedenceFactor,
    SOS1Factor,
    SOS2Factor,
    SubtourEliminationFactor,
)
from qqa.model.presolve import (
    PresolveInfeasibleError,
    PresolveReport,
    PresolveResult,
    presolve_model,
)

__all__ = [
    "AllDifferentFactor",
    "AssignmentFactor",
    "BlackBoxFactor",
    "CardinalityFactor",
    "ClauseFactor",
    "ConstraintIR",
    "CumulativeResourceFactor",
    "FlowConservationFactor",
    "HigherOrderFactor",
    "IndicatorFactor",
    "LinearFactor",
    "LogicalFactor",
    "MatchingFactor",
    "ModelIR",
    "ModelMetadata",
    "NoOverlapFactor",
    "ObjectiveIR",
    "ObjectiveSense",
    "PairwisePottsFactor",
    "PiecewiseLinearFactor",
    "PrecedenceFactor",
    "PresolveInfeasibleError",
    "PresolveReport",
    "PresolveResult",
    "QuadraticEdgeFactor",
    "SOS1Factor",
    "SOS2Factor",
    "SubtourEliminationFactor",
    "TableFactor",
    "TransformationRecord",
    "VariableBlock",
    "VariableDomain",
    "presolve_model",
]
