"""Portable result reports for notebooks, email, and experiment archives."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from qqa.visuals._data import serialisable_summary


def save_html_report(
    result: Any,
    problem: Any,
    path: str | Path,
    *,
    title: str | None = None,
    include_plotlyjs: bool | str = True,
) -> Path:
    """Write a self-contained interactive solver report.

    The report includes a four-panel diagnostic dashboard and an embedded
    machine-readable JSON payload. With the default ``include_plotlyjs=True``
    the HTML file works offline and can be shared as a single artifact.
    """
    try:
        from qqa.visualization import plot_result_dashboard
    except ImportError as exc:  # pragma: no cover - dependency failure
        raise ImportError(
            "HTML reports require Plotly. Install with `pip install qqa[plotly]`."
        ) from exc

    report_title = title or f"QQA optimisation report — {getattr(problem, 'name', 'problem')}"
    figure = plot_result_dashboard(
        result,
        problem,
        backend="plotly",
        title=report_title,
        show=False,
    )
    if not hasattr(figure, "to_html"):
        raise ImportError("HTML reports require Plotly. Install with `pip install qqa[plotly]`.")
    payload = serialisable_summary(result, problem)
    status = "FEASIBLE" if payload["feasible"] else "INFEASIBLE"
    status_class = "ok" if payload["feasible"] else "bad"
    chart = figure.to_html(
        full_html=False,
        include_plotlyjs=include_plotlyjs,
        config={"responsive": True, "displaylogo": False},
    )
    payload_json = json.dumps(payload, ensure_ascii=False, indent=2).replace("</", "<\\/")
    document = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(report_title)}</title>
  <style>
    :root {{ color-scheme: light dark; font-family: Inter, system-ui, sans-serif; }}
    body {{ max-width: 1320px; margin: 0 auto; padding: 2rem; background: #f8fafc; color: #0f172a; }}
    header {{ display: flex; gap: 1rem; align-items: center; justify-content: space-between; }}
    h1 {{ font-size: 1.55rem; margin: 0; }}
    .badge {{ padding: .4rem .7rem; border-radius: 999px; font-weight: 700; font-size: .8rem; }}
    .ok {{ color: #065f46; background: #d1fae5; }}
    .bad {{ color: #9f1239; background: #ffe4e6; }}
    .meta {{ display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .8rem; margin: 1.2rem 0; }}
    .card {{ background: white; border: 1px solid #e2e8f0; border-radius: .8rem; padding: .9rem; box-shadow: 0 1px 2px #0f172a12; }}
    .label {{ color: #64748b; font-size: .75rem; text-transform: uppercase; letter-spacing: .04em; }}
    .value {{ margin-top: .25rem; font-size: 1.05rem; font-weight: 650; overflow-wrap: anywhere; }}
    details {{ margin-top: 1rem; }}
    pre {{ max-height: 28rem; overflow: auto; padding: 1rem; border-radius: .6rem; background: #0f172a; color: #e2e8f0; }}
    footer {{ color: #64748b; font-size: .8rem; margin-top: 1.4rem; }}
    @media (max-width: 720px) {{ .meta {{ grid-template-columns: 1fr; }} body {{ padding: 1rem; }} }}
  </style>
</head>
<body>
  <header><h1>{html.escape(report_title)}</h1><span class="badge {status_class}">{status}</span></header>
  <section class="meta">
    <div class="card"><div class="label">Best penalised objective</div><div class="value">{html.escape(str(payload["best_obj"]))}</div></div>
    <div class="card"><div class="label">Reported score</div><div class="value">{html.escape(str(payload["score"].get("value", "n/a")))}</div></div>
    <div class="card"><div class="label">Runtime</div><div class="value">{payload["runtime_seconds"]:.4f} s</div></div>
  </section>
  <main>{chart}</main>
  <details><summary>Machine-readable result JSON</summary><pre>{html.escape(payload_json)}</pre></details>
  <script id="qqa-result" type="application/json">{payload_json}</script>
  <footer>Generated by QQA4CO · interactive and offline-ready</footer>
</body>
</html>
"""
    output = Path(path).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(document, encoding="utf-8")
    return output
